name: ItemRestrict
main: net.craftersland.itemrestrict.ItemRestrict
version: 2.1.1
author: CraftersLand
load: POSTWORLD
website: www.craftersland.net
commands:
    itemrestrict:
        description: Main command.
permissions:
    ItemRestrict.admin:
        description: Bypass restrictions and access to reload command.
        default: op
    ItemRestrict.bypass:
        description: Bypass restrictions.
        default: false