name: ItemRestrict
main: net.craftersland.itemrestrict.ItemRestrict
version: 2.4.2
api-version: 1.14
authors: [CraftersLand, Electro2560]
load: POSTWORLD
description: Item Restrict system.
commands:
    itemrestrict:
        description: Main command.
permissions:
    ItemRestrict.admin:
        description: Bypass restrictions and access to reload command.
        default: op
    ItemRestrict.bypass:
        description: Bypass restrictions.
        default: false